============================= test session starts ==============================
platform darwin -- Python 3.13.5, pytest-8.4.1, pluggy-1.6.0
rootdir: /Users/hich/Desktop/Bureau - MacbookAir HICHAM/PRO/GIT/data-engine
configfile: pytest.ini
plugins: anyio-4.9.0, Faker-37.4.0, dotenv-0.5.2
collected 5 items

tests/integration/test_training_pipeline.py .                            [ 20%]
tests/unit/test_feature_engineer.py ....                                 [100%]

=============================== warnings summary ===============================
../../../../../../../opt/homebrew/Caskroom/miniconda/base/envs/data-engine-py13/lib/python3.13/site-packages/_pytest/config/__init__.py:1474
  /opt/homebrew/Caskroom/miniconda/base/envs/data-engine-py13/lib/python3.13/site-packages/_pytest/config/__init__.py:1474: PytestConfigWarning: Unknown config option: dotenv_vars
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 5 passed, 1 warning in 1.12s =========================
